[workspace]
resolver = "2"
members = [
    "crates/vrl-caver-stdlib",
    "crates/caver-source-uf-compat",
    "crates/caver-sink-search-peer",
    "crates/caver-ottl-funcs",
    "crates/caver-sink-parquet",
    "crates/caver-ops",
]

[workspace.package]
version = "0.8.0"
edition = "2021"
license = "MPL-2.0"
