//! Golden-fixture tests for vrl-caver-stdlib OCSF normalization.
//!
//! Two test suites:
//!   golden_fixtures_are_valid — structural lint (every fixture parses and
//!     declares a non-zero class_uid)
//!   golden_{fixture} — snapshot tests that call normalize() and diff vs out.json
//!
//! Fixture directories are vendor-keyed (`<vendor>_<scenario>/`), not
//! class_uid-keyed: several vendors share one OCSF class (zeek conn and
//! suricata are both 4001) and one vendor spans several. For the vendors
//! mirrored from the Python collector transforms (#897) the out.json files
//! are generated BY those transforms — the snapshot asserts the Rust port
//! is byte-for-byte the same contract.
//!
//! Run with: cargo test --manifest-path caver/Cargo.toml

use std::path::PathBuf;
use vrl_caver_stdlib::ocsf;

fn golden_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent() // crates/
        .unwrap()
        .parent() // caver/
        .unwrap()
        .join("tests/golden")
}

/// Parses the file at `path` as JSON and returns the parsed value.
/// Panics with a descriptive message on failure.
fn load_json(path: &PathBuf) -> serde_json::Value {
    let raw = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("cannot read {}: {}", path.display(), e));
    serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("invalid JSON in {}: {}", path.display(), e))
}

#[test]
fn golden_fixtures_are_valid() {
    let dir = golden_dir();
    assert!(
        dir.exists(),
        "golden fixture directory not found: {}",
        dir.display()
    );

    let mut checked = 0u32;
    for entry in std::fs::read_dir(&dir).unwrap() {
        let entry = entry.unwrap();
        let fixture_dir = entry.path();
        if !fixture_dir.is_dir() {
            continue;
        }
        let name = fixture_dir
            .file_name()
            .unwrap()
            .to_string_lossy()
            .to_string();

        let in_path = fixture_dir.join("in.json");
        let out_path = fixture_dir.join("out.json");
        assert!(in_path.exists(), "missing in.json for fixture {name}");
        assert!(out_path.exists(), "missing out.json for fixture {name}");

        let in_val = load_json(&in_path);
        assert!(
            in_val
                .get("_vendor")
                .and_then(serde_json::Value::as_str)
                .is_some(),
            "in.json for fixture {name} must carry the _vendor routing tag"
        );

        let out = load_json(&out_path);
        let class_uid = out
            .get("class_uid")
            .and_then(serde_json::Value::as_u64)
            .unwrap_or_else(|| panic!("out.json for fixture {name} is missing numeric class_uid"));
        assert!(
            class_uid > 0,
            "out.json for fixture {name} has class_uid 0 (unclassified)"
        );

        checked += 1;
    }

    assert!(
        checked > 0,
        "no fixture directories found under {}",
        dir.display()
    );
    println!("golden: validated {checked} vendor fixture(s)");
}

// ---------------------------------------------------------------------------
// Snapshot tests — call normalize() and assert output matches out.json
// ---------------------------------------------------------------------------

fn run_normalize_snapshot(fixture: &str) {
    let dir = golden_dir().join(fixture);
    let in_val = load_json(&dir.join("in.json"));
    let expected = load_json(&dir.join("out.json"));
    let actual = ocsf::normalize(&in_val);
    assert_eq!(
        actual,
        expected,
        "normalize() mismatch for fixture {fixture}\n\
         actual:\n{}\n\
         expected:\n{}",
        serde_json::to_string_pretty(&actual).unwrap(),
        serde_json::to_string_pretty(&expected).unwrap(),
    );
}

#[test]
fn golden_okta_auth() {
    run_normalize_snapshot("okta_auth");
}

#[test]
fn golden_nginx_http() {
    run_normalize_snapshot("nginx_http");
}

#[test]
fn golden_sysmon_process_create() {
    run_normalize_snapshot("sysmon_process_create");
}

#[test]
fn golden_suricata_alert() {
    run_normalize_snapshot("suricata_alert");
}

#[test]
fn golden_zeek_conn() {
    run_normalize_snapshot("zeek_conn");
}

#[test]
fn golden_zeek_dns() {
    run_normalize_snapshot("zeek_dns");
}

#[test]
fn golden_palo_alto_traffic() {
    run_normalize_snapshot("palo_alto_traffic");
}

#[test]
fn golden_palo_alto_threat() {
    run_normalize_snapshot("palo_alto_threat");
}

#[test]
fn golden_fortinet_traffic() {
    run_normalize_snapshot("fortinet_traffic");
}

#[test]
fn golden_fortinet_event_auth() {
    run_normalize_snapshot("fortinet_event_auth");
}
